export { authService } from './auth';
export { workspacesService } from './workspaces';
export { getWorkspaceId, setWorkspaceId } from './client';
export { usersService } from './users';
export { userSchedulesService } from './userSchedules';
export { scheduleHolidaysService } from './scheduleHolidays';
export type { ScheduleBulkItem } from './userSchedules';
export { clientsService } from './clients';
export { clientGroupsService } from './clientGroups';
export { documentTypeGroupsService } from './documentTypeGroups';
export { activitiesService } from './activities';
export { activityTypesService } from './activityTypes';
export { workspaceBillingSettingsService } from './workspaceBillingSettings';
export { workspaceScheduleSettingsService } from './workspaceScheduleSettings';
export { invoiceConceptSettingsService } from './invoiceConceptSettings';
export { eventsService } from './events';
export { documentsService } from './documents';
export { reportsService } from './reports';
export type { ReportSummary } from './reports';
export { dashboardService } from './dashboard';
export { notificationsService } from './notifications';
export { savedTableViewsService } from './savedTableViews';
export { tableViewStateService } from './tableViewState';
export { userInteractionsService } from './userInteractions';
export type { DashboardStats } from './dashboard';
